# Generated by Django 6.0.5 on 2026-05-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hoodie', 'Hoodies'), ('joggers', 'Joggers'), ('shirts', 'Shirts'), ('jeans', 'Jeans'), ('bags', 'Bags'), ('shoes', 'Shoes')], default='shirts', max_length=20),
        ),
    ]
