# Generated by Django 6.0.5 on 2026-05-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_alter_product_image_url_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('hoodie', 'Hoodies'), ('joggers', 'Joggers'), ('shirts', 'Shirts'), ('jeans', 'Jeans'), ('bags', 'Bags'), ('footwear', 'Footwear')], default='shirts', max_length=20),
        ),
    ]
