# Generated by Django 6.0.5 on 2026-06-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('section_type', models.CharField(choices=[('brand_spotlight', 'Brand Spotlight'), ('new_arrivals', 'New Arrivals'), ('trending', 'Trending'), ('custom', 'Custom Section')], default='brand_spotlight', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('max_products', models.IntegerField(default=8, help_text='Maximum number of products to show')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['featured_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which brands appear on front page'),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='Order on front page (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on front page'),
        ),
    ]
