# Generated by Django 6.0.5 on 2026-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_featuredsection_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shirts', 'Shirts'), ('trousers', 'Trousers'), ('hoodie/sweatshirts', 'Hoodie/Sweatshirts'), ('joggers', 'Joggers'), ('footwear', 'Footwear'), ('others', 'Others')], default='shirts', max_length=20),
        ),
    ]
